let name = "Mo Kharboutli";
console.log("Name: " + name);
let wanted = true;
console.log("wanted: " + wanted);
const age = 17;
console.log("age: " + age);
let speed = 1000;
console.log("speed: " + speed);
let power = "super speed";
console.log("power: " + power);
let strength = 1000;
console.log("strength: " + strength);
let car = "honda civic";
console.log("car: " + car);
let score = 3452;
console.log("score: " + score);
let gun = "shotgun";
console.log("gun: " + gun);
let lives = 2;
console.log("lives left: " + lives);
